apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mt0glcwps-go 
  janus-idp.io/tekton: mt0glcwps-go
  backstage.io/kubernetes-id: mt0glcwps-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mt0glcwps-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml