apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mt0glcwps-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mt0glcwps-go 
  name: mt0glcwps-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mt0glcwps-go 
